default_platform(:ios)

platform :ios do
  desc "Build and deploy to the App Store"
  lane :deploy do
    setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_API_KEY_ID"],
      issuer_id: ENV["APPLE_API_ISSUER_ID"],
      key_filepath: ENV["APPLE_API_KEY_FILEPATH"]
    )
    match(
      type: "appstore",
      readonly: true,
      team_id: ENV["APPLE_TEAM_ID"],
      api_key: api_key,
      verbose: true
    )
    sh("flutter", "pub", "get")
    sh("pod", "install", "--repo-update")
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "eu.diatar.vetito" => ENV["MATCH_PROVISIONING_PROFILE_NAME"] || "match AppStore eu.diatar.vetito"
        }
      }
    )
    upload_to_app_store(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: true,
      automatic_release: true,
      force: true
    )
  end
end