default_platform(:android)

platform :android do
  desc "Build and deploy to the Play Store production track"
  lane :deploy do
    gradle(task: "clean")
    sh("flutter", "pub", "get")
    sh("flutter", "build", "appbundle", "--release")
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end